### ISSUE TITLE
Failure to push BCD-Extension caused by failure in CI

### ISSUE THREAD

**Issue by ZhiWei1010** [nus-cs2103-AY2324S2/forum#348]
Hi, After pushing my BCD-Extension into the fork, there is a failure caused by the CI. This also caused the grading bot to not detect the completion in the iP dashboard. 

Is there anyway to fix this?

<img width="1258" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/c1a3db43-9a60-477e-9110-e0e86e318c94">

<img width="1258" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/32d4a929-2290-4529-9d57-e7f918225392">

**Comment by damithc** [comment]
@ZhiWei1010 The two things are not related. As long as the `BCD-Extension` tag is in your fork (and reachable from the `master` branch, it will turn green in the dashboard).

**Comment by ZhiWei1010** [comment]
Ohh ok thanks prof. @damithc Is it ok to ignore the failure to merge message shown in the picture and for future commits as well?

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/525901c6-4f5f-4da0-92ed-a6c9dcec2a7f)

Also, I checked the tags in my master branch, the BCD-Extension exists but its not updated in the iP dashboard, not sure what is going on!

**Comment by UdhayaShan1** [comment]
If you just pushed, check again tomorrow the dashboard is updated daily only

**Comment by UdhayaShan1** [comment]
The failure is not merge failing but CI jobs failing, in this case (should be checkstyle errors)

**Comment by damithc** [comment]
> If you just pushed, check again tomorrow the dashboard is updated daily only

@UdhayaShan1 is correct. Check again after the next dashboard update.

**Comment by ZhiWei1010** [comment]
@UdhayaShan1 The tag was pushed before 2359 though, the other tags I pushed before 2359 today turned green except for this.

Also there were no warnings for any check style errors when I run the checkstyle gradle too!

**Comment by damithc** [comment]
> The tag was pushed before 2359 though

@ZhiWei1010  'updated daily' doesn't mean it's updated at 23.59 exactly :-p
You can see the dashboard update time at the top of the dashboard page.

**Comment by ZhiWei1010** [comment]
Oh ok that explains why haha! Thanks for the clarification prof @damithc  and also for your help @UdhayaShan1 !
Regarding the CI jobs failing will that be an issue or can I just ignore them?

**Comment by damithc** [comment]
> Regarding the CI jobs failing will that be an issue or can I just ignore them?

@ZhiWei1010 It is better to fix, as CI is not much use if it fails. For a start, you can compare what you changed between the  last commit that passed CI and the first commit that started failing CI. The failure seems to be coming from runtests.bat
See if you can run it locally.

**Comment by ZhiWei1010** [comment]
Hi prof @damithc , I have deleted the whole folder related to text-ui-test, so there is no runtest.sh and runtest.bash, but it seems like some error still persist when CI runs when I push my commits into the fork. 

This is the error:  'An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/ip/ip/text-ui-test'. No such file or directory'

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/60460444/fd2d0c9b-079e-4290-8548-34b4da8b8635)


Does this mean that the runtest.sh file is actually needed?

**Comment by simkianseng** [comment]
@ZhiWei1010 you might want to take a look at your `.github/workflows/gradle.yml` file. The CI failure is likely due to not being able to pass the tests listed in that file. Personally I removed `Perform IO redirection test (*NIX)`, `Perform IO redirection test (MacOS)`, and `Perform IO redirection test (Windows)` checks. Since in our latest iteration for iP we would be using GUI and not the CLI, hence I don't think the IO redirection tests would be relevant for our case. Hope this fixes your issue 😄 .

My `.github/workflows/gradle.yml` file:
```yml
name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@master

      - name: Set up repository
        uses: actions/checkout@master
        with:
          ref: master

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk+fx

      - name: Build and check with Gradle
        run: ./gradlew check
```
