### ISSUE TITLE
💎Automating Releases

### ISSUE THREAD

**Issue by drustanyjt** [nus-cs2103-AY2324S2/forum#697]
I was interested in finding a way to automate some parts of the release process. I ended up find this github action that helps (https://github.com/softprops/action-gh-release). This actions gets triggered every time an appropriate tag is pushed to the main team's repository, and helps create a draft release with the necessary `.jar` file uploaded. The relevant part of the workflow is here:

```
on:
  push:
    tags:
      - 'v1.*'

jobs:
  ...
      - name: Build Jar
        run: ./gradlew clean shadowJar

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          files: build/libs/clinicmate.jar
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
```

We also created a modified version of this that generates a release every night using a cron job.

I think it would be cool if it were possible to generate and attach the user guide as well. If anyone has tried doing that do share below!
