### ISSUE TITLE
Codecov no longer checking and commenting on pull requests

### ISSUE THREAD

**Issue by ibnu2651** [nus-cs2103-AY2324S2/forum#729]
I noticed that recently, some time in the past week, Codecov has stopped running its checks and commenting on our team's pull requests. Codecov still runs its checks when we merge the PR to the main branch and we can see the updated changes on the Codecov app so it should still have access to our repo. 

I'm not quite sure how to fix this or if this is intended behaviour, but if anyone has any idea or is experiencing the same thing that would be very helpful!

**Comment by yashpola** [comment]
Same here. Not sure why the checks have gone quiet either but its possible that its because in this period there are likely no changes to the code that necessitate coverage recalc?

**Comment by tzyian** [comment]
Facing the same issue for the past 2 days

```
['error'] There was an error running the uploader: 
Error uploading to [https://codecov.io:](https://codecov.io/) 
Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

Possibly relevant issue:
https://github.com/codecov/codecov-action/issues/557

**Comment by tzyian** [comment]
```
      - name: Upload coverage reports to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```

Have confirmed this works
Change `.github/workflows/gradle.yml` to use `v4`
i.e. from `uses: codecov/codecov-action@v3` to `uses: codecov/codecov-action@v4`
